name: FlameResolvePlus
version: '1.2.0'
main: dream.soulflame.flameresolveplus.FlameResolvePlus
authors: [ SoulFlame ]
depend:
  - FlameCore
  - PlaceholderAPI
commands:
  flameresolveplus:
    aliases:
      - frp
