name: FlameResolvePlus
version: '1.1.7'
main: dream.soulflame.flameresolveplus.FlameResolvePlus
authors: [ SoulFlame ]
depend:
  - FlameCore
  - PlaceholderAPI
commands:
  flameresolveplus:
    aliases:
      - frp
